site_name: Copilot Studio Agent Academy
site_url: https://microsoft.github.io/agent-academy/
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.tabs.link
    - toc.follow
    - content.code.copy
nav:
  - Home: index.md
  - Recruit:
      - Welcome: recruit/README.md
      - Course Setup: recruit/00-course-setup/README.md
      - Introduction to Agents: recruit/01-introduction-to-agents/README.md
      - Copilot Studio Fundamentals: recruit/02-copilot-studio-fundamentals/README.md
      - Create Declarative Agent: recruit/03-create-a-declarative-agent-for-M365Copilot/README.md
      - Create a Solution: recruit/04-creating-a-solution/README.md
      - Use Prebuilt Agents: recruit/05-using-prebuilt-agents/README.md
      - Create Agent from Conversation: recruit/06-create-agent-from-conversation/README.md
      - Add New Topic with Trigger: recruit/07-add-new-topic-with-trigger/README.md
      - Add Adaptive Card: recruit/08-add-adaptive-card/README.md
      - Add Agent Flow: recruit/09-add-an-agent-flow/README.md
      - Add Event Triggers: recruit/10-add-event-triggers/README.md
      - Publish Your Agent: recruit/11-publish-your-agent/README.md
      - Understanding Licensing: recruit/12-understanding-licensing/README.md
      - Secure Your Badge: recruit/course-completion-badges-recruit/README.md
  - Operative (Coming Soon): operative/README.md
  - Commander (Coming Soon): commander/README.md
repo_url: https://github.com/microsoft/agent-academy
repo_name: microsoft/agent-academy
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/includes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2
